### ISSUE TITLE
Transforms outputting to same file silently overwrite each other

### ISSUE THREAD

**Issue by alterae** [alterae/mksite#12]
Minimal reproduction:
```
.
├── layout
├── mksite.toml
├── src
│  ├── foo.1
│  └── foo.2
└── static
```
```toml
# mksite.toml
[transforms]
1.txt = "cat"
2.txt = "cat"
```
This will result in only one page called `foo.txt` in `out/`.

This behavior should probably be at least a warning, probably an error.
