### ISSUE TITLE
Templating/layout ignore lists

### ISSUE THREAD

**Issue by alterae** [alterae/mksite#5]
It should be possible to tell mksite to not do templating or layouts for certain files. Something like the `exclude` field in Cargo.toml, with globs. Useful for #1.

```toml
[ignore]
template = [ "**/*.{png, pdf}" ]
layout = [ "blog/my-special-page.html" ]
```
